[package]
name = "shoes"
version = "0.1.3"
edition = "2021"
license = "MIT"
description = "A multi-protocol proxy server."
homepage = "https://github.com/cfal/shoes/"
repository = "https://github.com/cfal/shoes/"
readme = "README.md"
keywords = ["proxy", "proxy-server", "shadowsocks", "v2ray", "vmess"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
aes = "*"
argon2 = "*"
async-trait = "*"
base64 = "*"
blake3 = "*"
cfb-mode = "*"
digest = "*"
env_logger = "*"
futures = "*"
hmac = "*"
log = "*"
md-5 = "*"
memchr = "*"
notify = "*"
parking_lot = "*"
percent-encoding = "*"
quinn = "*"
rand = "*"
ring = "*"
rustls = { version = "*", default-features = false, features = ["ring"] }
sha2 = "*"
sha3 = "*"
serde = { version = "*", features = ["derive", "std"] }
serde_yaml = "*"
tokio = { version = "*", features = [
    "fs",
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "sync",
    "time",
] }
tokio-rustls = { version = "*", default-features = false, features = ["logging", "tls12", "ring"] }
webpki-roots = { version = "*" }

[profile.release]
opt-level = 3
lto = "fat"
strip = true
